export type {
  AcademicProgram,
  Component,
  Course,
  CurriculumPlan,
  Grouping,
  Lifecycle,
  PlanVersion,
  Provenance,
  University,
  VersionCourse,
} from "./entities.js";
export type {
  AcademicProgramId,
  ComponentId,
  CourseId,
  CurriculumPlanId,
  GroupingId,
  OpaqueId,
  PlanVersionId,
  UniversityId,
  VersionCourseId,
} from "./identifiers.js";
export {
  courseCompleted,
  type AllRequirement,
  type AnyRequirement,
  type AtLeastRequirement,
  type CourseCompletedOrConcurrentRequirement,
  type CourseCompletedRequirement,
  type MinimumComponentCreditsRequirement,
  type MinimumGroupingCoursesRequirement,
  type MinimumGroupingCreditsRequirement,
  type MinimumTotalCreditsRequirement,
  type RequirementExpression,
  type RequirementLeaf,
} from "./requirements.js";
